let suggestions = [
    "RishBro",
    "Rishmika Sandanu",
    "MongoDB",
    "ImRishmika",
    "RishBroPromax",
    "YouTube",
    "YouTuber",
    "YouTube Channel",
    "Github",
    "Facebook",
    "Freelancer",
    "Instergram",
    "Designer",
    "Developer",
    "Web Designer",
    "Web Developer",
    "Login Form in HTML & CSS",
    "Mahida Rajapaksha College matara",
    "How to learn JavaScript",
    "Discrod",
    "How to become Web Designer",
    "How to start Gaming Channel",
    "How to start YouTube Channel",
    "What does HTML stands for?",
    "What does CSS stands for?",
];
